// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqsGZIwMVaYO2XzqZHLm38xItdMUFGy4',
    appId: '1:52261227893:web:a433a0b1bd50e461c9173c',
    messagingSenderId: '52261227893',
    projectId: 'ticketing-dc7e9',
    authDomain: 'ticketing-dc7e9.firebaseapp.com',
    databaseURL: 'https://ticketing-dc7e9-default-rtdb.firebaseio.com',
    storageBucket: 'ticketing-dc7e9.appspot.com',
    measurementId: 'G-EYYFR337XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_4MtQqDVCsV8Yq_v6xC-WgKCZSRrxT8',
    appId: '1:52261227893:android:7a4a94abcdb114d0c9173c',
    messagingSenderId: '52261227893',
    projectId: 'ticketing-dc7e9',
    databaseURL: 'https://ticketing-dc7e9-default-rtdb.firebaseio.com',
    storageBucket: 'ticketing-dc7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv2rTSYcsrJ7HV_kmfjCW4XstcRgwcjjU',
    appId: '1:52261227893:ios:b3c579143c99ca75c9173c',
    messagingSenderId: '52261227893',
    projectId: 'ticketing-dc7e9',
    databaseURL: 'https://ticketing-dc7e9-default-rtdb.firebaseio.com',
    storageBucket: 'ticketing-dc7e9.appspot.com',
    iosClientId: '52261227893-36i7f2qk5jcln6t5q5q8abo4je973u6c.apps.googleusercontent.com',
    iosBundleId: 'ml.samake.ticketiong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv2rTSYcsrJ7HV_kmfjCW4XstcRgwcjjU',
    appId: '1:52261227893:ios:b3c579143c99ca75c9173c',
    messagingSenderId: '52261227893',
    projectId: 'ticketing-dc7e9',
    databaseURL: 'https://ticketing-dc7e9-default-rtdb.firebaseio.com',
    storageBucket: 'ticketing-dc7e9.appspot.com',
    iosClientId: '52261227893-36i7f2qk5jcln6t5q5q8abo4je973u6c.apps.googleusercontent.com',
    iosBundleId: 'ml.samake.ticketiong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqsGZIwMVaYO2XzqZHLm38xItdMUFGy4',
    appId: '1:52261227893:web:bde2f528d8086c69c9173c',
    messagingSenderId: '52261227893',
    projectId: 'ticketing-dc7e9',
    authDomain: 'ticketing-dc7e9.firebaseapp.com',
    databaseURL: 'https://ticketing-dc7e9-default-rtdb.firebaseio.com',
    storageBucket: 'ticketing-dc7e9.appspot.com',
    measurementId: 'G-PRG53CVS1Q',
  );
}
